#!/usr/bin/env python3
__doc__ ='''
Converts day of year (doy) to date.


'''
Epilog = '''

:Examples:
::
    doy2date 262 # current year is 2016
    2016-09-18

    doy2date 262 2015
    2015-09-19

    With the current year as 2017:

    cat /tmp/test 
    70
    70 2015
    70

    cat /tmp/test | doy2date
    2017-03-11
    2015-03-11
    2017-03-11

Keywords: doy, day of year, date

COPYRIGHT:
   Copyright 2016, by the California Institute of Technology.
   ALL RIGHTS RESERVED.
   United States Government Sponsorship acknowledged.
'''

# Define author
__author__   = 'Willy Bertiger'

import sys, argparse # stdin
from datetime import datetime as datetime
from datetime import timedelta

def _getParser():
    argParser = argparse.ArgumentParser(description= __doc__, epilog=Epilog, 
                    #formatter_class=argparse.ArgumentDefaultsHelpFormatter)
                    formatter_class=argparse.RawDescriptionHelpFormatter ) 
                    #without this won't write verbatim

    argParser.add_argument('doy', metavar='doy', type=int, nargs='?', default=None,
                       help='day of year or read from stdin')

    argParser.add_argument('year', metavar='yyyy', type=int, nargs='?', default=None,
                       help='''optional year or read from stdin
                       from stdin the optional year is sticky, if set on one
                       line it remains the year if not set on another.
                       ''')
    return argParser

if __name__ == '__main__':
    args = _getParser().parse_args()

    fmt = '%Y-%m-%d'

    curYear = datetime.utcnow().year
    jan1 = datetime(curYear,1,1,12,0,0)

    if args.doy != None:
        if args.year != None:
            jan1 = datetime(args.year,1,1,12,0,0)
        delta = timedelta( args.doy - 1 )
        print( (jan1+delta).strftime(fmt) )
    else:
        for l in sys.stdin:
            a = l.split()
            if len(a) > 1:
                jan1 = datetime(int(a[1]),1,1,12,0,0)
            else:
                jan1 = datetime(curYear,1,1,12,0,0)
            delta = timedelta( int(a[0]) - 1)
            print( (jan1+delta).strftime(fmt) )

